### ISSUE TITLE
Let the website url of the repo point to the deployed cheatsheet

### ISSUE THREAD

**Issue by realvictorprm** [digital-asset/daml-cheat-sheet#15]
Right now the link on the front page of the repository points to the daml website but not to the deployed cheatsheet. I think it would be better to let it point to https://docs.daml.com/cheat-sheet

**Comment by nemanja-da** [comment]
Can you give more info (e.g., a screenshot) on what exactly you'd like to change?

**Comment by realvictorprm** [comment]
sure :)

In classic open source projects these days, this link usual refers to the website of the library. Refering to daml itself isn't that wrong, but as this is the repository for the cheatsheet I would have expected that it directly links to page where the deployed version of the cheat sheet can be found.

![image](https://user-images.githubusercontent.com/25414896/122892951-282ad800-d346-11eb-9437-93eb39b44711.png)

**Comment by nemanja-da** [comment]
Don't really see a reason for changing it to docs.daml.com as Daml's repo is also pointing to daml.com. This makes it consistent

**Comment by realvictorprm** [comment]
It should not point to the docs in general, but directly to the location of the cheatsheet. What I'm suggesting here is common practice for open source projects to my knowledge.

**Comment by garyverhaegen-da** [comment]
Done. @nemanja-da hopefully now what he meant is clearer; if you still think `daml.com` is better I can chang eback. Please confirm either way.

**Comment by nemanja-da** [comment]
Thnx @realvictorprm and @garyverhaegen-da for your comments! Got it 😃

**Comment by realvictorprm** [comment]
perfect, thanks folks! :smiley:
